export const environment = {
  production: false,
  baseURL: 'http://localhost:3000/',

  // BearingCatalog

  GetDoublerowdeepgroove: 'bearing-catalogue/api/GetDoublerowdeepgroove',
  GetSinglerowcontactball: 'bearing-catalogue/api/GetSinglerowcontactball',

  GetAdapterassembliesshperical: 'bearing-catalogue/api/GetAdapterassembliesshperical',
  GetAdapterassemlies: 'bearing-catalogue/api/GetAdapterassemlies',
  GetCombinedneedlemetricseries: 'bearing-catalogue/api/GetCombinedneedlemetricseries',
  GetCombinedneedlemetricseries2: 'bearing-catalogue/api/GetCombinedneedlemetricseries2',
  GetDoubledirectionthrust: 'bearing-catalogue/api/GetDoubledirectionthrust',
  GetDoublerowcontactball: 'bearing-catalogue/api/GetDoublerowcontactball',
  GetDoublerowcylidrical: 'bearing-catalogue/api/GetDoublerowcylidrical',
  GetDrawcupneedleinchseries: 'bearing-catalogue/api/GetDrawcupneedleinchseries',
  GetDrawcupneedlemetricseries: 'bearing-catalogue/api/GetDrawcupneedlemetricseries',
  GetExtendedinnerringtype: 'bearing-catalogue/api/GetExtendedinnerringtype',
  GetExtrasmallminiatureballbearings: 'bearing-catalogue/api/GetExtrasmallminiatureballbearings',
  GetFlangedtype: 'bearing-catalogue/api/GetFlangedtype',
  GetHeavydutyneedleinchseries: 'bearing-catalogue/api/GetHeavydutyneedleinchseries',
  GetHeavydutyneedleinnerrings: 'bearing-catalogue/api/GetHeavydutyneedleinnerrings',
  GetHeavydutyneedlemetricseries: 'bearing-catalogue/api/GetHeavydutyneedlemetricseries',
  GetMatchedpair: 'bearing-catalogue/api/GetMatchedpair',
  GetMiniatureonewayclutches: 'bearing-catalogue/api/GetMiniatureonewayclutches',
  GetNeedlerollermetricseries: 'bearing-catalogue/api/GetNeedlerollermetricseries',
  GetNeedlerollermetricseries2: 'bearing-catalogue/api/GetNeedlerollermetricseries2',
  GetNeedlerollerthrustinchseries: 'bearing-catalogue/api/GetNeedlerollerthrustinchseries',
  GetNeedlerollerthrustmetricseries: 'bearing-catalogue/api/GetNeedlerollerthrustmetricseries',
  GetNeedlerollerthrustmetricseries2: 'bearing-catalogue/api/GetNeedlerollerthrustmetricseries2',
  GetRadialneedleinchseries: 'bearing-catalogue/api/GetRadialneedleinchseries',
  GetRadialneedlemetricseries: 'bearing-catalogue/api/GetRadialneedlemetricseries',
  GetSelfaligningopentype: 'bearing-catalogue/api/GetSelfaligningopentype',
  GetSelfaligningsealedtype: 'bearing-catalogue/api/GetSelfaligningsealedtype',
  GetSerialnoindex: 'bearing-catalogue/api/GetSerialnoindex',
  GetSingledirctionthrust: 'bearing-catalogue/api/GetSingledirctionthrust',
  GetSinglerowcylindrical: 'bearing-catalogue/api/GetSinglerowcylindrical',
  Getsinglerowinchseries: 'bearing-catalogue/api/Getsinglerowinchseries',
  GetSinglerowmetricseries: 'bearing-catalogue/api/GetSinglerowmetricseries',
  GetSinglerowopentype: 'deepgroove/singlerowopentype',
  // GetSinglerowopentype: 'bearing-catalogue/api/getsinglerowopentype',
  GetSinglerowsealedtype: 'deepgroove/singlerowsealedtype',
  GetSinglerowsnapringgroovetype: 'deepgroove/singlerowsnapringgroovetype',
  GetSphericalrollerbearings: 'bearing-catalogue/api/GetSphericalrollerbearings',
  GetTditype: 'bearing-catalogue/api/GetTditype',
  GetTdotype: 'bearing-catalogue/api/GetTdotype',
  GetThrustcollars: 'bearing-catalogue/api/GetThrustcollars',
  GetWithdrawalsleeves: 'bearing-catalogue/api/GetWithdrawalsleeves',
  GetGetsphericalthrustroller: 'bearing-catalogue/api/GetGetsphericalthrustroller',
};
